export const filters = [
    {
      id: "roles",
      label: "Roles",
      placeholder: "Roles",
      multiple: true,
      options: [
        { title: "Backend Developer", value: "Backend Developer" },
        { title: "Frontend Developer", value: "Frontend Developer" },
        { title: "Full Stack Developer", value: "Full Stack Developer" },
        { title: "Software Engineer", value: "Software Engineer" },
        { title: "DevOps Engineer", value: "DevOps Engineer" },
        { title: "Network Engineer", value: "Network Engineer" },
        { title: "Database Administrator", value: "Database Administrator" },
        { title: "Systems Administrator", value: "Systems Administrator" },
        { title: "UI/UX Designer", value: "UI/UX Designer" },
        { title: "Product Designer", value: "Product Designer" },
        { title: "Graphic Designer", value: "Graphic Designer" },
        { title: "Operations Manager", value: "Operations Manager" },
        { title: "Project Manager", value: "Project Manager" },
        {
          title: "Quality Assurance Engineer",
          value: "Quality Assurance Engineer",
        },
        { title: "Data Scientist", value: "Data Scientist" },
        {
          title: "Machine Learning Engineer",
          value: "Machine Learning Engineer",
        },
        { title: "Cybersecurity Analyst", value: "Cybersecurity Analyst" },
        {
          title: "Technical Support Engineer",
          value: "Technical Support Engineer",
        },
      ],
    },
    {
      id: "employees",
      label: "No Of Employees",
      placeholder: "No Of Employees",
      multiple: true,
      options: [
        {
          title: "1-10",
          value: "1-10",
        },
        {
          title: "11-20",
          value: "11-20",
        },
        {
          title: "51-100",
          value: "51-100",
        },
        {
          title: "101-200",
          value: "101-200",
        },
        {
          title: "201-500",
          value: "201-500",
        },
        {
          title: "500+",
          value: "500+",
        },
      ],
    },
    {
      id: "experience",
      label: "Experience",
      placeholder: "Experience",
      multiple: false,
      options: [
        { title: "1", value: "1" },
        { title: "2", value: "2" },
        { title: "3", value: "3" },
        { title: "4", value: "4" },
        { title: "5", value: "5" },
        { title: "6", value: "6" },
        { title: "7", value: "7" },
        { title: "8", value: "8" },
        { title: "9", value: "9" },
        { title: "10", value: "10" },
      ],
    },
    {
      id: "remote",
      label: "Remote",
      placeholder: "Remote",
      multiple: true,
      options: [
        { title: "Remote", value: "remote" },
        { title: "Hybrid", value: "hybrid" },
        { title: "In-Office", value: "in-office" },
      ],
    },
    {
      id: "minBasePay",
      label: "Min Base Pay",
      placeholder: "Min Base Pay",
      multiple: false,
      options: [
        { title: "0L", value: "0L" },
        { title: "10L", value: "10L" },
        { title: "20L", value: "20L" },
        { title: "30L", value: "30L" },
        { title: "40L", value: "40L" },
        { title: "50L", value: "50L" },
        { title: "60L", value: "60L" },
        { title: "70L", value: "70L" },
      ],
    },
  ];
