export const filters = [
    {
      id: "roles",
      label: "Roles",
      placeholder: "Roles",
      multiple: true,
      options: [
        { "title": "Backend Developer", "value": "backend" },
        { "title": "Frontend Developer", "value": "frontend" },
        { "title": "Full Stack Developer", "value": "fullstack" },
        { "title": "Software Engineer", "value": "software" },
        { "title": "DevOps Engineer", "value": "devops" },
        { "title": "Network Engineer", "value": "network" },
        { "title": "Database Administrator", "value": "database" },
        { "title": "Systems Administrator", "value": "systems" },
        { "title": "UI/UX Designer", "value": "ui" },
        { "title": "Product Designer", "value": "product" },
        { "title": "Graphic Designer", "value": "graphic" },
        { "title": "Operations Manager", "value": "operations" },
        { "title": "Project Manager", "value": "project" },
        { "title": "Quality Assurance Engineer", "value": "quality" },
        { "title": "Data Scientist", "value": "data" },
        { "title": "Machine Learning Engineer", "value": "machine" },
        { "title": "Cybersecurity Analyst", "value": "cybersecurity" },
        { "title": "Technical Support Engineer", "value": "technical" }
      ],
    },
    {
      id: "employees",
      label: "No Of Employees",
      placeholder: "No Of Employees",
      multiple: true,
      options: [
        {
          title: "1-10",
          value: "1-10",
        },
        {
          title: "11-20",
          value: "11-20",
        },
        {
          title: "51-100",
          value: "51-100",
        },
        {
          title: "101-200",
          value: "101-200",
        },
        {
          title: "201-500",
          value: "201-500",
        },
        {
          title: "500+",
          value: "500+",
        },
      ],
    },
    {
      id: "experience",
      label: "Experience",
      placeholder: "Experience",
      multiple: false,
      options: [
        { title: "1", value: "1" },
        { title: "2", value: "2" },
        { title: "3", value: "3" },
        { title: "4", value: "4" },
        { title: "5", value: "5" },
        { title: "6", value: "6" },
        { title: "7", value: "7" },
        { title: "8", value: "8" },
        { title: "9", value: "9" },
        { title: "10", value: "10" },
      ],
    },
    {
      id: "remote",
      label: "Remote",
      placeholder: "Remote",
      multiple: true,
      options: [
        { title: "Remote", value: "remote" },
        { title: "Hybrid", value: "hybrid" },
        { title: "In-Office", value: "in-office" },
      ],
    },
    {
      id:'techStacks',
      label:"Tech Stack",
      placeholder: "Tech Stack",
      multiple: true,
      options:[
        { "title": "JavaScript", "value": "javascript" },
        { "title": "Python", "value": "python" },
        { "title": "Java", "value": "java" },
        { "title": "C++", "value": "c++" },
        { "title": "C#", "value": "c#" },
        { "title": "Ruby", "value": "ruby" },
        { "title": "Swift", "value": "swift" },
        { "title": "Go", "value": "go" },
        { "title": "TypeScript", "value": "typescript" },
        { "title": "Kotlin", "value": "kotlin" },
        { "title": "React", "value": "react" },
        { "title": "Angular", "value": "angular" },
        { "title": "Vue.js", "value": "vue" },
        { "title": "Node.js", "value": "node" },
        { "title": "Express.js", "value": "express" },
        { "title": "Django", "value": "django" },
        { "title": "Spring Boot", "value": "spring" },
        { "title": "Ruby on Rails", "value": "rails" },
        { "title": "Flutter", "value": "flutter" },
        { "title": "Unity", "value": "unity" },
        { "title": "Docker", "value": "docker" },
        { "title": "Kubernetes", "value": "kubernetes" },
        { "title": "Git", "value": "git" },
        { "title": "Jenkins", "value": "jenkins" },
        { "title": "AWS", "value": "aws" },
        { "title": "Azure", "value": "azure" },
        { "title": "Google Cloud", "value": "gcp" },
        { "title": "MySQL", "value": "mysql" },
        { "title": "PostgreSQL", "value": "postgresql" },
        { "title": "MongoDB", "value": "mongodb" }
      ]
    },
    {
      id: "minBasePay",
      label: "Min Base Pay",
      placeholder: "Min Base Pay",
      multiple: false,
      options: [
        { title: "0L", value: "0L" },
        { title: "10L", value: "10L" },
        { title: "20L", value: "20L" },
        { title: "30L", value: "30L" },
        { title: "40L", value: "40L" },
        { title: "50L", value: "50L" },
        { title: "60L", value: "60L" },
        { title: "70L", value: "70L" },
      ],
    },
  ];
